import React, { useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { trackPageView, trackButtonClick } from '@/lib/telemetry';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { Check, Shield, Lock, Users } from 'lucide-react';

export default function Gesundheitswesen() {
  const navigate = useNavigate();

  useEffect(() => {
    // Track pageview with metadata
    trackPageView('Gesundheitswesen');
    
    // Track with custom metadata for campaign tracking
    const eventData = {
      event_type: 'page_view' as const,
      event_name: 'Gesundheitswesen Landing Page',
      user_agent: navigator.userAgent,
      referrer: document.referrer || undefined,
      page_url: window.location.href,
      page_path: window.location.pathname,
      metadata: {
        source: 'reddit',
        campaign: 'pflege_lite',
      },
    };
    
    // Save to analytics_events table (session_id will be auto-generated by telemetry)
    supabase
      .from('analytics_events')
      .insert([eventData])
      .then(({ error }) => {
        if (error) {
          console.error('[Analytics] Failed to save event:', error);
        } else {
          console.log('[Analytics] Event tracked:', eventData);
        }
      });
    
    // SEO Meta Tags
    const title = 'Pflege: Jobwechsel ohne echte Einblicke | BeVisiblle';
    const description = 'Kurzes Profil erstellen und Zugang zu Austausch & echten Einblicken erhalten – bevor du dich bewirbst.';
    
    document.title = title;
    
    // Update or create meta description
    let metaDesc = document.querySelector('meta[name="description"]');
    if (!metaDesc) {
      metaDesc = document.createElement('meta');
      metaDesc.setAttribute('name', 'description');
      document.head.appendChild(metaDesc);
    }
    metaDesc.setAttribute('content', description);
    
    // Cleanup on unmount
    return () => {
      // Optionally restore default title
    };
  }, []);

  const handleCTAClick = () => {
    // Track CTA click with metadata
    trackButtonClick('Kurzes Profil erstellen (5 Minuten)', 'cta');
    
    // Track CTA click with campaign metadata
    const eventData = {
      event_type: 'button_click' as const,
      event_name: 'Kurzes Profil erstellen (5 Minuten)',
      button_label: 'Kurzes Profil erstellen (5 Minuten)',
      button_type: 'cta',
      user_agent: navigator.userAgent,
      referrer: document.referrer || undefined,
      page_url: window.location.href,
      page_path: window.location.pathname,
      metadata: {
        source: 'reddit',
        campaign: 'pflege_lite',
        action: 'cta_click',
      },
    };
    
    supabase
      .from('analytics_events')
      .insert([eventData])
      .then(({ error }) => {
        if (error) {
          console.error('[Analytics] Failed to save CTA click:', error);
        }
      });
    
    // Navigate with UTM params
    navigate('/cv-generator?utm_source=reddit&utm_medium=cpc&utm_campaign=pflege_lite&utm_content=lite_lp');
  };

  return (
    <div className="min-h-screen bg-white flex flex-col">
      {/* Simplified Header - Only Logo */}
      <header className="w-full border-b border-gray-100">
        <div className="mx-auto max-w-5xl px-4 py-3">
          <Link to="/" className="flex items-center gap-2">
            <img 
              src="/assets/Logo_visiblle-2.svg" 
              alt="BeVisiblle" 
              className="h-8 w-8" 
            />
            <span className="text-lg font-semibold tracking-tight">
              BeVisib<span className="text-primary">ll</span>e
            </span>
          </Link>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1 flex items-center justify-center px-4 py-12 md:py-16">
        <div className="w-full max-w-[640px] mx-auto">
          {/* Image Section - Top */}
          <div className="mb-8 md:mb-12">
            <img 
              src="/assets/Cluster1.png" 
              alt="Pflegekräfte bei BeVisiblle - Community" 
              className="w-full h-auto rounded-2xl shadow-lg object-cover max-h-[300px] md:max-h-[400px]"
            />
          </div>

          <div className="text-center space-y-8">
            {/* Headline */}
            <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold text-gray-900 leading-tight">
              Jobwechsel ohne echte Einblicke ist ein Risiko.
            </h1>

          {/* Subheadline */}
          <p className="text-lg md:text-xl text-gray-600 leading-relaxed">
            Viele merken erst nach dem Start, dass Alltag, Team und Erwartungen ganz anders sind.
          </p>

          {/* Bullets */}
          <div className="space-y-4 text-left max-w-md mx-auto">
            <div className="flex items-start gap-3">
              <div className="flex-shrink-0 mt-1">
                <Check className="h-5 w-5 text-primary" />
              </div>
              <p className="text-base md:text-lg text-gray-700">
                echte Einblicke von Mitarbeitenden
              </p>
            </div>
            <div className="flex items-start gap-3">
              <div className="flex-shrink-0 mt-1">
                <Check className="h-5 w-5 text-primary" />
              </div>
              <p className="text-base md:text-lg text-gray-700">
                unabhängiger Austausch
              </p>
            </div>
            <div className="flex items-start gap-3">
              <div className="flex-shrink-0 mt-1">
                <Check className="h-5 w-5 text-primary" />
              </div>
              <p className="text-base md:text-lg text-gray-700">
                Orientierung vor dem Bewerben
              </p>
            </div>
          </div>

          {/* Social Proof - Avatar Cluster */}
          <div className="flex items-center justify-center gap-3 pt-4">
            <div className="flex -space-x-2">
              {[1, 2, 3, 4].map((i) => (
                <img
                  key={i}
                  src={`https://i.pravatar.cc/40?img=${i + 10}`}
                  alt={`Profil ${i}`}
                  className="w-10 h-10 rounded-full border-2 border-white shadow-sm object-cover"
                />
              ))}
            </div>
            <span className="text-sm font-medium text-gray-700">
              Über 500 Pfleger bereits dabei
            </span>
          </div>

          {/* Primary CTA */}
          <div className="space-y-4 pt-6">
            <Button
              onClick={handleCTAClick}
              size="lg"
              className="w-full md:w-auto px-8 py-6 text-base md:text-lg font-semibold bg-[#5170ff] hover:bg-[#3d5ae8] text-white rounded-lg shadow-lg hover:shadow-xl transition-all"
              data-source="reddit"
              data-campaign="pflege_lite"
            >
              Kurzes Profil erstellen (5 Minuten)
            </Button>
            
            {/* Trust Badges */}
            <div className="flex flex-wrap items-center justify-center gap-4 text-xs text-gray-600">
              <div className="flex items-center gap-1.5">
                <Shield className="h-4 w-4 text-green-600" />
                <span>DSGVO-konform</span>
              </div>
              <div className="flex items-center gap-1.5">
                <Lock className="h-4 w-4 text-blue-600" />
                <span>Deine Daten bleiben privat</span>
              </div>
              <div className="flex items-center gap-1.5">
                <Users className="h-4 w-4 text-purple-600" />
                <span>Keine Weitergabe</span>
              </div>
            </div>
            
            {/* Trust line */}
            <p className="text-sm text-gray-500">
              Kostenlos · keine Bewerbung · kein Verkauf
            </p>
          </div>

          {/* Optional micro section - only if space allows */}
          <div className="pt-8 space-y-3 max-w-lg mx-auto">
            <h2 className="text-xl font-semibold text-gray-900">
              Warum ein kurzes Profil?
            </h2>
            <p className="text-base text-gray-600 leading-relaxed">
              Damit wir dir relevante Einblicke & Austausch zeigen können – ohne Zeit zu verschwenden. Kein Bewerben · keine Weitergabe · du entscheidest selbst.
            </p>
          </div>
        </div>
      </main>

      {/* Minimal Footer */}
      <footer className="border-t border-gray-100 py-6">
        <div className="mx-auto max-w-5xl px-4">
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 sm:gap-6 text-sm text-gray-600">
            <Link 
              to="/datenschutz" 
              className="hover:text-gray-900 transition-colors"
            >
              Datenschutz
            </Link>
            <span className="hidden sm:inline text-gray-300">·</span>
            <Link 
              to="/impressum" 
              className="hover:text-gray-900 transition-colors"
            >
              Impressum
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}

