-- Seed missing vocab_tags with conflict on existing unique(key)
INSERT INTO public.vocab_tags (key, label, type)
VALUES
('buero-kfm','Kaufmann/-frau für Büromanagement','profession'),
('fi-ae','Fachinformatiker/in Anwendungsentwicklung','profession'),
('fi-si','Fachinformatiker/in Systemintegration','profession'),
('elektroniker-energie-gebaeude','Elektroniker/in für Energie- und Gebäudetechnik','profession'),
('mechatroniker','Mechatroniker/in','profession'),
('anlagenmechaniker-shk','Anlagenmechaniker/in SHK','profession'),
('industriemechaniker','Industriemechaniker/in','profession'),
('kfz-mechatroniker','Kfz-Mechatroniker/in','profession'),
('friseur','Friseur/in','profession'),
('mfa','Medizinische/r Fachangestellte/r (MFA)','profession'),
('zuverlaessig','Zuverlässig','must'),
('teamfaehig','Teamfähig','must'),
('lernbereit','Lernbereit','must'),
('puenktlich','Pünktlich','must'),
('sorgfaeltig','Sorgfältig','must'),
('kommunikativ','Kommunikativ','must'),
('eigenverantwortlich','Eigenverantwortlich','must'),
('kundenorientiert','Kundenorientiert','must'),
('prog-grundkenntnisse','Grundkenntnisse Programmierung','nice'),
('praktika-erfahrung','Erste Praktika-Erfahrung','nice'),
('fuehrerschein-b','Führerschein Klasse B','nice'),
('englisch','Englischkenntnisse','nice'),
('office','Office-Kenntnisse','nice'),
('handwerkliches-geschick','Handwerkliches Geschick','nice'),
('kleines-team','Kleines Team','work_env'),
('junges-team','Junges Team','work_env'),
('strukturierte-ausbildung','Strukturierte Ausbildung','work_env'),
('viel-praxis','Viel Praxis','work_env'),
('moderne-werkstatt','Moderne Werkstatt','work_env'),
('remote-anteile','Remote-Anteile','work_env'),
('oepnv-zuschuss','ÖPNV-Zuschuss','benefit'),
('mitarbeiterrabatte','Mitarbeiterrabatte','benefit'),
('arbeitsgeraet','Laptop/Arbeitsgerät','benefit'),
('weiterbildung','Weiterbildung','benefit'),
('azubi-events','Azubi-Events','benefit'),
('uebernahmemoeglichkeit','Übernahmemöglichkeit','benefit'),
('flexible-zeiten','Flexible Arbeitszeiten','benefit'),
('schueler','Schüler/in','target_group'),
('azubi','Azubi','target_group'),
('ausgelernt','Geselle/ausgelernt','target_group')
ON CONFLICT (key) DO NOTHING;